api.ribbon.listOfServers=backend-service:8081
# ensure eureka isn't used
eureka.shouldFetchRegistry=false
eureka.client.enabled=false
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
# Use configuration-based server list for the 'api' client so ribbon reads listOfServers
api.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
