api.ribbon.listOfServers=backend:8081
eureka.shouldFetchRegistry=false
eureka.client.enabled=false
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
api.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList